- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "21206554+isCordial@users.noreply.github.com"
  tags:
  - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "isCordial"
  tags:
  - git-personal

