  - name: Install productivity packages
    apt:
      name: [ "tmux", "fzf" ]
    become: true
    tags:
    - misc
    - productivity

  - name: Install tmux plugin manager
    ansible.builtin.git:
      repo: 'https://github.com/tmux-plugins/tpm'
      dest: '~/.tmux/plugins/tpm'
    become_user: t
    tags:
    - misc
    - productivity
