- name: Make nvm directory
  shell: mkdir /home/t/.nvm
  tags:
  - node

- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
  - node

- name: Add node to path
  become: true
  lineinfile:
    path: /etc/environment
    line: PATH="$HOME/.nvm/versions/node/$(nvm current)/bin:$PATH"
  tags:
  - node
#
# - name: Install nodejs and npm
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#   tags:
#     - install
#     - node
#
# - name: npmjs prefix
#   shell: mkdir -p ~/.local/.npm-global
#   tags:
#   - install
#   - node
#
# - name: add npmjs to path
#   shell: PATH=$HOME/.local/.npm-global/bin:$PATH
#   tags:
#   - install
#   - node
#
# - name: npmjs global settings
#   shell: npm config set prefix '~/.local/.npm-global'
#   tags:
#   - install
#   - node
#
# - name: npmjs global settings export path in case I don't have dotfiles installed
#   shell: export PATH=~/.local/.npm-global/bin:$PATH
#   tags:
#   - install
#   - node
#   - npm
#   
# - name: Install N
#   npm:
#     name: n
#     global: yes
#   tags:
#     - install
#     - node
#
# - name: N prefix directory
#   shell: mkdir -p ~/.local/.n
#   tags:
#   - install
#   - node
#
# - name: add N to path
#   shell: N_PREFIX=$HOME/.local/.n
#   tags:
#   - install
#   - node
#
# - name: Set N_PREFIX export
#   shell: export N_PREFIX=$HOME/.local/.n
#   tags:
#   - install
#   - node
#
# - name: n-install 
#   shell: curl -L https://bit.ly/n-install | bash
#   tags:
#   - install
#   - node
#
# - name: Install correct version of Node
#   shell: ~/.local/.npm-global/bin/n lts
#   tags:
#     - install
#     - node
