  - name: Install apt packages
    apt:
      name: [ "build-essential", "python3", "pip", "universal-ctags" ]
      state: present
    become: true
    tags:
    - deps

  - name: Install pip packages
    pip:
      name: [ "aider-chat" ]
      state: present
    tags:
    - python
    - deps
