  - name: Install zsh
    apt: name=zsh
    tags:
    - zsh

  - name: Change shell to zsh
    shell: sudo chsh -s $(which zsh)
    tags:
    - zsh

  - name: Check ohmyzsh dir exists
    stat:
      path: /home/t/.oh-my-zsh
    register: oh_my_stats
    tags:
    - zsh

  - name: Install ohmyzsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    when: oh_my_stats.stat.exists == False
    become: true
    tags:
    - zsh

  - name: Install ohmyzsh auto-completions
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
    tags:
    - zsh

  # - name: update zshrc
  #   shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
  #   tags:
  #   - zsh