  - name: Install zsh
    apt: name=zsh
    tags:
    - zsh
  - name: Change shell
    shell: sudo chsh -s $(which zsh) $(whoami)
    tags:
    - zsh
  - name: Install ohmyzsh
    shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    tags:
    - zsh
  - name: Install ohmyzsh auto-completions
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions'
      dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
    tags:
    - zsh
  - name: update zshrc
    shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
    tags:
    - zsh
